version: '3.9'

services:
  db:
    image: postgres:16
    container_name: helpdesk_db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build: .
    container_name: helpdesk_web
    entrypoint: ["./entrypoint.sh"]
    # O comando foi atualizado para Gunicorn, como planejamos para produção
    command: ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  adminer:
    image: adminer
    container_name: helpdesk_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata: