# Generated by Django 5.2 on 2025-04-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=20, verbose_name='Status'),
        ),
    ]
