# Generated by Django 5.2 on 2025-06-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_anexo_comentario_alter_anexo_chamado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Nota interna'),
        ),
    ]
